### ISSUE TITLE
Setup correct DNS

### ISSUE THREAD

**Issue by manurodriguez** [manurodriguez/ansible_advance_homework#53]
Openstack instances get a wrong DNS which makes instances to take time to response and pull packages since the resolv.conf loops in the list, then provide correct DNS IPs
```
- name: Configuration of Subnets for Public and Private SubNets
  os_subnet:
...
    dns_nameservers:
      - 8.8.8.7
      - 8.8.8.8
```
